#### 1. Import the numpy package under the name `np` (★☆☆)

In [50]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [51]:
print(np.__version__)
np.show_config()

1.24.2

openblas64__info:

    libraries = ['openblas64_', 'openblas64_']

    library_dirs = ['openblas\\lib']

    language = c

    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]

    runtime_library_dirs = ['openblas\\lib']

blas_ilp64_opt_info:

    libraries = ['openblas64_', 'openblas64_']

    library_dirs = ['openblas\\lib']

    language = c

    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]

    runtime_library_dirs = ['openblas\\lib']

openblas64__lapack_info:

    libraries = ['openblas64_', 'openblas64_']

    library_dirs = ['openblas\\lib']

    language = c

    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]

    runtime_library_dirs = ['openblas\\lib']

lapack_ilp64_opt_info:

    libraries = ['openblas64_', 'openblas64_']

    library_dirs = ['openblas\\lib']

    language = c

    define_macros

#### 3. Create a null vector of size 10 (★☆☆)

In [52]:
vector = np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [53]:
vector = np.zeros((50,75))
print(f"{(vector.size * zVector.itemsize)} bytes" )

30000 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [54]:
np.info(np.add) #python -c "import numpy as np; np.info(np.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])



Add arguments element-wise.



Parameters

----------

x1, x2 : array_like

    The arrays to be added.

    If ``x1.shape != x2.shape``, they must be broadcastable to a common

    shape (which becomes the shape of the output).

out : ndarray, None, or tuple of ndarray and None, optional

    A location into which the result is stored. If provided, it must have

    a shape that the inputs broadcast to. If not provided or None,

    a freshly-allocated array is returned. A tuple (possible only as a

    keyword argument) must have length equal to the number of outputs.

where : array_like, optional

    This condition is broadcast over the input. At locations where the

    condition is True, the `out` array will be set to the ufunc result.

    Elsewhere, the `out` array will retain its original value.

    Note that if an uninitialized `out` array is created via th

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [55]:
vector = np.zeros(10)
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [56]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33

 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [62]:
n = int(input("Enter the size of list : "))
vector = np.arange(n)
vector = vector[::-1]
print(vector)

Enter the size of list :  40


[39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16

 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [63]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]

 [3 4 5]

 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [119]:
non_zeroes_indices = np.nonzero([1,2,0,0,4,0])
print(non_zeroes_indices)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [120]:
matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]

 [0. 1. 0.]

 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [121]:
matrix = 100*np.random.random((3,3,3))
print(matrix)

[[[65.32420832  5.88009438 29.35896265]

  [83.09597782 51.37944493 81.31696164]

  [ 9.56208308 93.0761145  19.79729831]]



 [[80.53061694 71.31851238 41.16922322]

  [50.76011613 74.5962485  49.83403948]

  [70.46395491 12.82327763 99.15187253]]



 [[ 4.17897245 62.14377101 54.18249339]

  [94.01572117 21.47080571 81.26489726]

  [25.41403655  5.27054859 96.58817139]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [122]:
matrix = 100*np.random.random((10,10)).round(3)
print(matrix)
matrixrMin, matrixMax = matrix.min(), matrix.max()
print(f"Minimum is: {matrixrMin}; Maximum is {matrixMax}" )

[[98.8 93.8 75.1 78.3 12.3 72.1 94.5 71.3 73.4 64.7]

 [64.1 85.9 63.8 98.6 61.7 17.1 75.9 67.  27.3 94.8]

 [40.8 57.  40.7 72.8 54.  88.1 62.9 43.5 12.9 36.4]

 [42.5 43.  36.9  5.  93.6 61.3 68.7  6.3 54.5 72.3]

 [39.8 89.8 32.3 13.5 75.7 51.7 19.9 66.5 95.2 55.7]

 [58.4 89.9 42.3 21.  37.3 13.1 74.7 62.  21.7 18.2]

 [13.5 45.2 27.8  9.1 46.3  9.3 12.1 34.8 65.9 73.2]

 [25.  92.7 31.4 72.9 88.4  8.  36.3 77.6 97.3 58.3]

 [22.3 44.8 12.6  3.9 22.6 74.2 19.6 17.9 80.4 39.5]

 [91.1 29.3  5.2 48.5  9.2 73.7 35.9 51.6 66.3 48.9]]

Minimum is: 3.9; Maximum is 98.8


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [123]:
vector = 100*np.random.random(30).round(1)
print(vector)
avgValue = vector.mean()
print(avgValue)

[ 90.  50.  80.   0.  10.  70.  20.  10.  10.  90.  70.  50.  10.  90.

  60.  90.  10.  30.  70.  10. 100.  30. 100.  70. 100.  20.  70.  30.

  50.  60.]

51.666666666666664


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [124]:
matrix = np.ones((10,10))
matrix[1:-1, 1:-1] = 0
print(matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]

 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]

 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]

 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]

 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]

 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]

 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]

 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]

 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [125]:
matrix = np.ones((5,5))
matrix = np.pad(matrix, pad_width=1, mode='constant', constant_values=0)
print(matrix)

[[0. 0. 0. 0. 0. 0. 0.]

 [0. 1. 1. 1. 1. 1. 0.]

 [0. 1. 1. 1. 1. 1. 0.]

 [0. 1. 1. 1. 1. 1. 0.]

 [0. 1. 1. 1. 1. 1. 0.]

 [0. 1. 1. 1. 1. 1. 0.]

 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [126]:
print(f"0 * np.nan={0 * np.nan}")
print(f"np.nan == np.nan={np.nan == np.nan}")
print(f"np.inf > np.nan={np.inf > np.nan}")
print(f"np.nan - np.nan={np.nan - np.nan}")
print(f"np.nan in set([np.nan])={np.nan in set([np.nan])}")
print(f"0.3 == 3 * 0.1={0.3 == 3 * 0.1}")


0 * np.nan=nan

np.nan == np.nan=False

np.inf > np.nan=False

np.nan - np.nan=nan

np.nan in set([np.nan])=True

0.3 == 3 * 0.1=False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [127]:
matrix = np.diag(1+np.arange(4),k=-1)
print(matrix)

[[0 0 0 0 0]

 [1 0 0 0 0]

 [0 2 0 0 0]

 [0 0 3 0 0]

 [0 0 0 4 0]]


# 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [128]:
matrix = np.zeros((8,8),dtype=int)
matrix[1::2,::2] = 1
matrix[::2,1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]

 [1 0 1 0 1 0 1 0]

 [0 1 0 1 0 1 0 1]

 [1 0 1 0 1 0 1 0]

 [0 1 0 1 0 1 0 1]

 [1 0 1 0 1 0 1 0]

 [0 1 0 1 0 1 0 1]

 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [129]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [130]:
matrix = np.tile( np.array([ [0,1], [1,0] ]), (4,4))
print(matrix)

[[0 1 0 1 0 1 0 1]

 [1 0 1 0 1 0 1 0]

 [0 1 0 1 0 1 0 1]

 [1 0 1 0 1 0 1 0]

 [0 1 0 1 0 1 0 1]

 [1 0 1 0 1 0 1 0]

 [0 1 0 1 0 1 0 1]

 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [141]:
matrix = np.random.random((5,5))
maxValue =matrix.max() 
matrix /= maxValue
matrix

array([[0.89457488, 0.40310156, 0.71008254, 0.29865689, 0.9681213 ],
       [0.57937121, 0.33264952, 0.24176039, 0.86188443, 0.47786357],
       [0.10948772, 0.6678361 , 0.89442442, 1.        , 0.56389913],
       [0.00876142, 0.90197839, 0.34055969, 0.36402789, 0.51204941],
       [0.35935914, 0.50806354, 0.01483946, 0.44855118, 0.44035652]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [143]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [146]:
matrix2 = np.ones((5,3)) @ np.ones((3,2))
print(matrix2)

[[3. 3.]

 [3. 3.]

 [3. 3.]

 [3. 3.]

 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [148]:
vector = np.arange(11)
vector[3:9] = np.multiply(vector[3:9],-1)
print(vector)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [149]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [152]:
Z = np.arange(10, dtype=int)
print(f"Z**Z = {Z**Z}")
print(f"2 << Z >> 2 = {2 << Z >> 2}")
print(f"Z <- Z = {Z <- Z}")
print(f"1j*Z = {1j*Z}")
print(f"Z/1/1 = {Z/1/1}")
print(f"Z<Z>Z = {Z<Z>Z}")

Z**Z = [        1         1         4        27       256      3125     46656

    823543  16777216 387420489]

2 << Z >> 2 = [  0   1   2   4   8  16  32  64 128 256]

Z <- Z = [False False False False False False False False False False]

1j*Z = [0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]

Z/1/1 = [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [153]:
print(f"np.array(0) / np.array(0) = {np.array(0) / np.array(0)}")
print(f"np.array(0) // np.array(0) = {np.array(0) // np.array(0)}")
print(f"np.array([np.nan]).astype(int).astype(float) = {np.array([np.nan]).astype(int).astype(float)}")

np.array(0) / np.array(0) = nan

np.array(0) // np.array(0) = 0

np.array([np.nan]).astype(int).astype(float) = [-2.14748365e+09]


C:\Users\Paul\AppData\Local\Temp\ipykernel_14600\3821006838.py:1: RuntimeWarning: invalid value encountered in divide

  print(f"np.array(0) / np.array(0) = {np.array(0) / np.array(0)}")

C:\Users\Paul\AppData\Local\Temp\ipykernel_14600\3821006838.py:2: RuntimeWarning: divide by zero encountered in floor_divide

  print(f"np.array(0) // np.array(0) = {np.array(0) // np.array(0)}")

C:\Users\Paul\AppData\Local\Temp\ipykernel_14600\3821006838.py:3: RuntimeWarning: invalid value encountered in cast

  print(f"np.array([np.nan]).astype(int).astype(float) = {np.array([np.nan]).astype(int).astype(float)}")


#### 29. How to round away from zero a float array ? (★☆☆)

In [157]:
vector = np.random.uniform(-10,10,10)
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[-10.   1.   3.  -7.  -8.  -2.   3.  -7.  -8.   7.]


#### 30. How to find common values between two arrays? (★☆☆)

In [170]:
vector1 = np.random.randint(10,40,10)
vector2 = np.random.randint(39,50,10)
print(np.intersect1d(vector1,vector2))

[39]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [173]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [174]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [175]:
_ = np.seterr(**defaults)

In [176]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\Paul\AppData\Local\Temp\ipykernel_14600\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt

  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [178]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(f"Yesterday: {yesterday}, Today: {today}. Tomorrow: {tomorrow}")

Yesterday: 2023-03-28, Today: 2023-03-29. Tomorrow: 2023-03-30


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [179]:
vectorDates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(vectorDates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'

 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'

 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'

 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'

 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'

 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'

 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [182]:
A = np.ones(5)*10
B = np.ones(5)*20
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-150., -150., -150., -150., -150.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [185]:
vector = np.random.uniform(0,10,10)
print(vector)
print(vector - vector%1)
print(vector // 1)
print(np.floor(vector))
print(vector.astype(int))

[5.46571539 9.35890215 3.05228169 2.43209675 3.44212612 7.68151354

 2.07469127 9.29378136 2.36691521 1.60192986]

[5. 9. 3. 2. 3. 7. 2. 9. 2. 1.]

[5. 9. 3. 2. 3. 7. 2. 9. 2. 1.]

[5. 9. 3. 2. 3. 7. 2. 9. 2. 1.]

[5 9 3 2 3 7 2 9 2 1]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [186]:
matrix = np.zeros((5,5))
matrix += np.arange(5)
print(matrix)

[[0. 1. 2. 3. 4.]

 [0. 1. 2. 3. 4.]

 [0. 1. 2. 3. 4.]

 [0. 1. 2. 3. 4.]

 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [194]:
def generate():
    for val in range(10):
        yield val
vector = np.fromiter(generate(), dtype=int)
print(vector)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [198]:
vector = np.linspace(0,1,11,endpoint=False)[1:]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455

 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [200]:
vector = 100* np.random.random(10)
vector.sort()
print(vector)

[24.02527404 31.98905574 38.82774759 48.23471133 48.41411587 51.05726135

 54.51291229 78.89804699 79.87845685 95.87923271]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [203]:
vector = np.arange(10)
print(vector)
np.add.reduce(vector)

[0 1 2 3 4 5 6 7 8 9]


45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [208]:
A = np.random.randint(0,10,10)
print(A)

B = np.random.randint(0,10,10)
print(B) 
print(np.array_equal(A,B))

[9 4 9 3 9 9 2 0 3 5]

[8 9 1 0 5 6 7 0 3 5]

False


#### 43. Make an array immutable (read-only) (★★☆)

In [210]:
vector = np.zeros(15)
vector.flags.writeable = False
vector[3] = 5

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [213]:
matrix = np.random.random((10,2))
X,Y = matrix[:,0], matrix[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.08711426 0.12806499 0.99452686 0.74098685 0.23038195 0.77215091

 0.98944664 0.81646254 0.97806504 0.79806872]

[0.45875524 1.31107747 0.60011771 1.34713033 0.81246864 0.91743295

 1.4585973  1.26340668 0.81642266 1.13063689]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [216]:
vector = np.random.random(10)
print(vector)
print()
vector[vector.argmax()] = 0
print(vector)

[0.25612154 0.16642975 0.89159263 0.39234551 0.04504213 0.69376925

 0.63906897 0.41871167 0.55103991 0.71205977]



[0.25612154 0.16642975 0.         0.39234551 0.04504213 0.69376925

 0.63906897 0.41871167 0.55103991 0.71205977]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [220]:
vector = np.zeros((6,6), [('x',float),('y',float)])
vector['x'], vector['y'] = np.meshgrid(np.linspace(0,1,6),
                             np.linspace(0,1,6))
print(vector)

[[(0. , 0. ) (0.2, 0. ) (0.4, 0. ) (0.6, 0. ) (0.8, 0. ) (1. , 0. )]

 [(0. , 0.2) (0.2, 0.2) (0.4, 0.2) (0.6, 0.2) (0.8, 0.2) (1. , 0.2)]

 [(0. , 0.4) (0.2, 0.4) (0.4, 0.4) (0.6, 0.4) (0.8, 0.4) (1. , 0.4)]

 [(0. , 0.6) (0.2, 0.6) (0.4, 0.6) (0.6, 0.6) (0.8, 0.6) (1. , 0.6)]

 [(0. , 0.8) (0.2, 0.8) (0.4, 0.8) (0.6, 0.8) (0.8, 0.8) (1. , 0.8)]

 [(0. , 1. ) (0.2, 1. ) (0.4, 1. ) (0.6, 1. ) (0.8, 1. ) (1. , 1. )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [224]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(C)

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818

  -0.15384615 -0.13333333]

 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222

  -0.18181818 -0.15384615]

 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429

  -0.22222222 -0.18181818]

 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4

  -0.28571429 -0.22222222]

 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667

  -0.4        -0.28571429]

 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.

  -0.66666667 -0.4       ]

 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.

  -2.         -0.66666667]

 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667

   2.         -2.        ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [225]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128

127

-2147483648

2147483647

-9223372036854775808

9223372036854775807

-3.4028235e+38

3.4028235e+38

1.1920929e-07

-1.7976931348623157e+308

1.7976931348623157e+308

2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [238]:
vector = np.ones((10,10), dtype=int)
print(vector)

[[1 1 1 1 1 1 1 1 1 1]

 [1 1 1 1 1 1 1 1 1 1]

 [1 1 1 1 1 1 1 1 1 1]

 [1 1 1 1 1 1 1 1 1 1]

 [1 1 1 1 1 1 1 1 1 1]

 [1 1 1 1 1 1 1 1 1 1]

 [1 1 1 1 1 1 1 1 1 1]

 [1 1 1 1 1 1 1 1 1 1]

 [1 1 1 1 1 1 1 1 1 1]

 [1 1 1 1 1 1 1 1 1 1]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [254]:
vector = np.arange(100, 0, -2)
print(vector)
scalar = np.random.uniform(0,100)
print(scalar)
index = (np.abs(vector-scalar)).argmin()
print(vector[index])

[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66

  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30

  28  26  24  22  20  18  16  14  12  10   8   6   4   2]

86.28134381179166

86


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [261]:
vector = np.zeros(10, [ ('position', [ ('x', float),
                                       ('y', float)]),
                       
                        ('color',    [ ('r', float),
                                       ('g', float),
                                       ('b', float)])])
print(vector)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))

 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))

 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))

 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))

 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [328]:
vector = np.random.random((25,2))
X,Y = np.atleast_2d(vector[:,0], vector[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.2380221  0.50579366 0.53250143 0.57722221 0.69152239

  0.53853598 0.76120495 0.77129165 0.42728263 0.58191086 0.25293515

  0.64207402 0.81221196 0.49783151 0.31001788 0.18617204 0.28114

  0.48154816 0.51496168 0.69444408 0.07511894 0.50294575 0.34708838

  0.76196677]

 [0.2380221  0.         0.7434006  0.62388009 0.53366077 0.85266362

  0.77429941 0.87031936 0.95209744 0.55460261 0.6475996  0.46533795

  0.76295607 0.9591588  0.39783811 0.53611519 0.37825238 0.47878028

  0.70921342 0.70376048 0.93078141 0.25709225 0.67017384 0.28939671

  0.88169306]

 [0.50579366 0.7434006  0.         0.68798449 0.92210507 0.60609542

  0.12773699 0.79368931 0.59206343 0.56801707 0.7650582  0.32473048

  0.68655643 0.73066614 0.91757152 0.23947385 0.43785885 0.38880719

  0.14449344 0.42397059 0.22573456 0.50874904 0.49259118 0.77132319

  0.76829808]

 [0.53250143 0.62388009 0.68798449 0.         0.32381032 0.3032542

  0.60950246 0.24706895 0.43381257 0.12671533 0.07755173 0.682

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [266]:
vectorFloats = (np.random.rand(10)*100).astype(np.float32)
print(vectorFloats)
vectorInts = vectorFloats.view(np.int32)
vectorInts[:] = vectorFloats
print(vectorInts)

[54.744595  92.61033   90.356926  95.03598   60.771957   6.482016

  1.1692487 61.28374   64.231544  56.91139  ]

[54 92 90 95 60  6  1 61 64 56]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [269]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
readFile = np.genfromtxt(s, delimiter=",", dtype=int)
print(readFile)

[[ 1  2  3  4  5]

 [ 6 -1 -1  7  8]

 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [272]:
matrix = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(matrix):
    print(index, value)
for index in np.ndindex(matrix.shape):
    print(index, matrix[index])

(0, 0) 0

(0, 1) 1

(0, 2) 2

(1, 0) 3

(1, 1) 4

(1, 2) 5

(2, 0) 6

(2, 1) 7

(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [273]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818

  0.57375342 0.51979489 0.44822088 0.36787944]

 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367

  0.69905581 0.63331324 0.54610814 0.44822088]

 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308

  0.81068432 0.73444367 0.63331324 0.51979489]

 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382

  0.89483932 0.81068432 0.69905581 0.57375342]

 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022

  0.9401382  0.85172308 0.73444367 0.60279818]

 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022

  0.9401382  0.85172308 0.73444367 0.60279818]

 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382

  0.89483932 0.81068432 0.69905581 0.57375342]

 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308

  0.81068432 0.73444367 0.63331324 0.51979489]

 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.7344436

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [274]:
n = 10
p = 3
matrix = np.zeros((n,n))
np.put(matrix, np.random.choice(range(n*n), p, replace=False),1)
print(matrix)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]

 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]

 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [279]:
X = np.random.rand(5, 10)
meanvalue = X.mean(axis=1, keepdims=True)
print(f"Mean value vector: {meanvalue}")
print()
Y = X - meanvalue
print(X)
print()
print(Y)


Mean value vector: [[0.41556203]

 [0.49940067]

 [0.45583078]

 [0.71597667]

 [0.68419177]]



[[0.77479856 0.47659687 0.12873907 0.68847913 0.43222101 0.27461699

  0.50565634 0.20097095 0.25986042 0.41368094]

 [0.74331951 0.94745554 0.47418245 0.19695716 0.19868202 0.76158281

  0.02089452 0.21082683 0.82722785 0.61287804]

 [0.40152363 0.24838354 0.23763083 0.61094656 0.18330379 0.74965654

  0.07288373 0.62300709 0.45693472 0.97403736]

 [0.22447314 0.75465735 0.97019498 0.57551992 0.98438182 0.8081364

  0.77178308 0.88630795 0.57844694 0.6058651 ]

 [0.52276323 0.96361594 0.89461965 0.08597298 0.83039141 0.98772096

  0.94066906 0.82720243 0.16424563 0.62471643]]



[[ 0.35923654  0.06103484 -0.28682296  0.2729171   0.01665899 -0.14094504

   0.09009432 -0.21459108 -0.15570161 -0.00188109]

 [ 0.24391884  0.44805487 -0.02521822 -0.30244351 -0.30071866  0.26218213

  -0.47850616 -0.28857384  0.32782718  0.11347737]

 [-0.05430715 -0.20744724 -0.21819995  0.15511578 -0.27252699 

#### 59. How to sort an array by the nth column? (★★☆)

In [284]:
vector = np.random.randint(0,10,(3,3))
print(vector)
print()
print(vector[vector[:,1].argsort()])

[[5 5 2]

 [9 4 4]

 [4 8 2]]



[[9 4 4]

 [5 5 2]

 [4 8 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [309]:
matrix = np.random.randint(0,2,(5,10))
print(matrix)
print((~matrix.any(axis=0)).any())

[[0 0 1 1 1 0 0 1 1 1]

 [0 1 1 0 1 0 0 0 0 0]

 [0 1 1 1 0 0 0 1 1 0]

 [1 1 1 1 1 1 0 0 0 0]

 [1 0 0 1 1 0 0 1 1 0]]

True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [310]:
matrix = np.random.uniform(0,1,10)
print(matrix)
givenValue = 0.5
print()
print(givenValue)
print()
nearestInArray = matrix.flat[np.abs(matrix - givenValue).argmin()]
print(nearestInArray)

[0.65490179 0.6109094  0.80304859 0.93478105 0.81587437 0.2506327

 0.27171234 0.69510331 0.80560688 0.49827302]



0.5



0.49827302233669124


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [314]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]

 [1 2 3]

 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [321]:
class ArrayWithName(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

myArray = ArrayWithName(np.arange(10), "MyArrayName")
print (myArray.name)

MyArrayName


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [323]:
vector = np.ones(10)
print(vector)
indicesVec = np.random.randint(0,len(vector),20)
print(indicesVec)
vector += np.bincount(indicesVec, minlength=len(vector))
print(vector)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[0 1 3 0 0 7 4 9 3 5 2 7 8 5 4 1 8 9 8 5]

[4. 3. 2. 3. 3. 4. 1. 3. 4. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [326]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [327]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [334]:
A = np.random.randint(0,10,(4,4,4,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[52 73 75 73]

 [79 78 74 79]

 [85 88 56 54]

 [61 64 63 54]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [335]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.55608423 0.37154379 0.51993677 0.44768486 0.41619959 0.54196074

 0.32727306 0.40952106 0.4964714  0.44039386]


#### 69. How to get the diagonal of a dot product? (★★★)

In [341]:
A = 100*np.random.uniform(0,1,(5,5))
print(A)
print()
B = 100*np.random.uniform(0,1,(5,5))
print(B)
print()
print(np.sum(A * B.T, axis=1))
print(np.diag(np.dot(A, B)))


[[49.80931401 76.90172509 72.15585743 98.64723287 47.41707205]

 [63.87320117 30.63580105 14.69187638 67.17064381 43.27617372]

 [93.53786774 69.42600744 73.13762915 35.5547059  25.33514046]

 [ 6.41483683 74.52279099  7.34244281 21.87846987 16.29680488]

 [77.17454116 73.31891003 34.28363356 98.99446376 21.17726196]]



[[66.68744616 23.15172602 10.22384889 52.72214175 37.85359205]

 [96.59234123 66.22027954  7.87412459 24.00827376 54.86172719]

 [58.1830338  64.51746522 81.39161254 94.37304187 31.26982155]

 [65.72063473  3.48851608 99.65823468 11.63474903 62.59262783]

 [91.75960052 14.22743987 83.52076198 97.49857157 10.64382867]]



[25782.15065853  5305.40381659 13115.10509187  4663.76187063

 14437.50951673]

[25782.15065853  5305.40381659 13115.10509187  4663.76187063

 14437.50951673]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [342]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [343]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]

  [2. 2. 2.]

  [2. 2. 2.]

  [2. 2. 2.]

  [2. 2. 2.]]



 [[2. 2. 2.]

  [2. 2. 2.]

  [2. 2. 2.]

  [2. 2. 2.]

  [2. 2. 2.]]



 [[2. 2. 2.]

  [2. 2. 2.]

  [2. 2. 2.]

  [2. 2. 2.]

  [2. 2. 2.]]



 [[2. 2. 2.]

  [2. 2. 2.]

  [2. 2. 2.]

  [2. 2. 2.]

  [2. 2. 2.]]



 [[2. 2. 2.]

  [2. 2. 2.]

  [2. 2. 2.]

  [2. 2. 2.]

  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [347]:
A = np.arange(25).reshape(5,5)
A[[0,4]] = A[[4,0]]
print(A)

[[20 21 22 23 24]

 [ 5  6  7  8  9]

 [10 11 12 13 14]

 [15 16 17 18 19]

 [ 0  1  2  3  4]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [348]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 46) ( 0, 59) ( 1, 35) ( 1, 89) ( 9, 38) ( 9, 63) (13, 24) (13, 83)

 (24, 83) (34, 71) (34, 76) (35, 89) (38, 63) (38, 87) (38, 93) (44, 67)

 (44, 85) (46, 59) (47, 76) (47, 99) (48, 74) (48, 79) (54, 66) (54, 97)

 (66, 97) (67, 85) (71, 76) (74, 79) (76, 99) (87, 93)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [349]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [352]:
def moving_average(a, n) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

vector = np.arange(20)
print(moving_average(vector, n=4))

[ 1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5 11.5 12.5 13.5 14.5

 15.5 16.5 17.5]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [354]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
vector = rolling(np.arange(10), 3)
print(vector)

[[0 1 2]

 [1 2 3]

 [2 3 4]

 [3 4 5]

 [4 5 6]

 [5 6 7]

 [6 7 8]

 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [375]:
vector = np.random.uniform(-1.0,1.0,10)
print(vector)
print()
print(np.negative(vector, out=vector))

[-0.3948177  -0.51902953  0.89968683  0.25872312 -0.16149469 -0.80986675

 -0.77568734 -0.87427464 -0.33144168 -0.37421727]



[ 0.3948177   0.51902953 -0.89968683 -0.25872312  0.16149469  0.80986675

  0.77568734  0.87427464  0.33144168  0.37421727]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [361]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[5.23123305 1.66992989 7.57434731 6.13086441 1.13637037 2.75820828

 2.72684134 6.00132124 3.41228932 4.49037925]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [362]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 2.88844937  3.95422019  8.28284287  2.16804538  8.21662733  4.72337096

   3.07161517  3.91498959 14.51745565  4.93986329]

 [10.81014881 10.02337254  8.54899653 11.74152274 23.86661225  5.29135633

   9.95593583  3.13513289  0.13550447  4.8817454 ]

 [ 5.79926161  5.78687688  1.8491424   5.68160381  7.28680132  7.58219106

   8.03672184  8.32619085  4.35051719  7.13156126]

 [ 4.22548838  3.33939038  8.5248027   7.64405146  3.86189128  0.19799863

   0.4030278   3.20975636 11.93408732  2.2586624 ]

 [ 2.54426871  1.75379775  7.35339641  5.82438797  5.61765087  0.07735209

   0.71858958  2.11218332 11.38354454  1.10062576]

 [ 5.40318769  5.00726145  4.10946749  5.57227648 17.78157998  5.05051523

   8.25531528  0.04112943  2.60653461  1.48506937]

 [ 0.89487498  1.10522552  1.85461732  0.63871273 11.23251218  2.73310812

   4.52925847  1.4992187   7.02439597  0.24416687]

 [ 5.06486755  5.46810139  2.41933359  2.23792198 13.32437974  0.81266892

   1.77171093  3.04882807  9.2749426

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [372]:
vector = np.arange(1,15,dtype=np.uint32)
stridedMatrix = stride_tricks.as_strided(vector,(11,4),(4,4))
print(stridedMatrix)

[[ 1  2  3  4]

 [ 2  3  4  5]

 [ 3  4  5  6]

 [ 4  5  6  7]

 [ 5  6  7  8]

 [ 6  7  8  9]

 [ 7  8  9 10]

 [ 8  9 10 11]

 [ 9 10 11 12]

 [10 11 12 13]

 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [371]:
matrix = np.random.uniform(0,1,(10,10))
rank = np.linalg.matrix_rank(matrix)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [376]:
vector = np.random.randint(0,10,50)
print(np.bincount(vector).argmax())

8


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [383]:
from numpy.lib.stride_tricks import sliding_window_view
vector = np.random.randint(0,5,(10,10))
print(vector)
print()
print(sliding_window_view(vector, window_shape=(3, 3)))

[[2 4 2 4 0 0 3 1 4 2]

 [0 2 0 2 4 1 0 0 3 0]

 [4 0 3 1 1 0 4 1 2 1]

 [1 3 1 1 2 1 4 1 3 1]

 [4 3 4 0 3 4 4 0 2 0]

 [3 0 3 2 3 2 4 3 2 3]

 [2 2 4 0 2 2 4 4 0 2]

 [2 0 2 4 0 1 4 2 3 4]

 [0 2 0 1 1 0 2 0 1 2]

 [4 4 1 4 2 1 0 2 0 1]]



[[[[2 4 2]

   [0 2 0]

   [4 0 3]]



  [[4 2 4]

   [2 0 2]

   [0 3 1]]



  [[2 4 0]

   [0 2 4]

   [3 1 1]]



  [[4 0 0]

   [2 4 1]

   [1 1 0]]



  [[0 0 3]

   [4 1 0]

   [1 0 4]]



  [[0 3 1]

   [1 0 0]

   [0 4 1]]



  [[3 1 4]

   [0 0 3]

   [4 1 2]]



  [[1 4 2]

   [0 3 0]

   [1 2 1]]]





 [[[0 2 0]

   [4 0 3]

   [1 3 1]]



  [[2 0 2]

   [0 3 1]

   [3 1 1]]



  [[0 2 4]

   [3 1 1]

   [1 1 2]]



  [[2 4 1]

   [1 1 0]

   [1 2 1]]



  [[4 1 0]

   [1 0 4]

   [2 1 4]]



  [[1 0 0]

   [0 4 1]

   [1 4 1]]



  [[0 0 3]

   [4 1 2]

   [4 1 3]]



  [[0 3 0]

   [1 2 1]

   [1 3 1]]]





 [[[4 0 3]

   [1 3 1]

   [4 3 4]]



  [[0 3 1]

   [3 1 1]

   [3 4 0]]



  [[3 1 1]

   [1 1 2]

   [4 0 3]]



  [[1 1 0]

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [384]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 1 16  3  6  6]

 [16  5 11  9 16]

 [ 3 11  3 42 12]

 [ 6  9 42  7 13]

 [ 6 16 12 13  7]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [385]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]

 [200.]

 [200.]

 [200.]

 [200.]

 [200.]

 [200.]

 [200.]

 [200.]

 [200.]

 [200.]

 [200.]

 [200.]

 [200.]

 [200.]

 [200.]

 [200.]

 [200.]

 [200.]

 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [386]:
vector = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(vector, np.arange(0, vector.shape[0], k), axis=0),
                                       np.arange(0, vector.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]

 [16. 16. 16. 16.]

 [16. 16. 16. 16.]

 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [388]:
def iterate(vector):
    N = (vector[0:-2,0:-2] + vector[0:-2,1:-1] + vector[0:-2,2:] +
         vector[1:-1,0:-2]                + vector[1:-1,2:] +
         vector[2:  ,0:-2] + vector[2:  ,1:-1] + vector[2:  ,2:])

    birth = (N==3) & (vector[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (vector[1:-1,1:-1]==1)
    vector[...] = 0
    vector[1:-1,1:-1][birth | survive] = 1
    return vector

vector = np.random.randint(0,2,(50,50))
for i in range(100): vector = iterate(vector)
print(vector)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

  0 0 0 0 0 0 0 0 0 0 0 0 0 0]

 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

  0 0 0 0 0 0 0 0 0 0 0 0 0 0]

 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

  0 0 0 0 0 0 0 0 0 0 0 0 0 0]

 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

  0 0 0 0 0 0 0 0 0 0 0 0 0 0]

 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

  0 0 0 0 0 0 0 0 0 0 0 0 0 0]

 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

  0 0 0 0 0 0 0 0 0 0 0 0 0 0]

 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

  0 0 0 0 0 0 0 0 0 0 0 0 0 0]

 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0

  0 0 0 0 0 0 0 0 0 0 0 0 0 0]

 [0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0

  0 0 0 0 0 0 0 0 0 0 0 0 0 0]

 [0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [390]:
vector = np.arange(10000)
np.random.shuffle(Z)
n = 10
print(vector[np.argsort(vector)[-n:]])
print(vector[np.argpartition(-vector,n)[:n]])

[9990 9991 9992 9993 9994 9995 9996 9997 9998 9999]

[9992 9996 9993 9998 9991 9994 9995 9997 9999 9990]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [391]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]

 [1 4 7]

 [1 5 6]

 [1 5 7]

 [2 4 6]

 [2 4 7]

 [2 5 6]

 [2 5 7]

 [3 4 6]

 [3 4 7]

 [3 5 6]

 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [392]:
vector = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
record = np.core.records.fromarrays(vector.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(record)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [397]:
x = np.random.rand(int(5e6))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

153 ms ± 1.81 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

22.1 ms ± 371 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

13.8 ms ± 358 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [398]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 5 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [400]:
matrix = np.random.randint(0,5,(10,3))
print(matrix)

E = np.all(matrix[:,1:] == matrix[:,:-1], axis=1)
U = matrix[~E]
print(U)
U = matrix[matrix.max(axis=1) != matrix.min(axis=1),:]
print(U)

[[2 2 4]

 [3 4 3]

 [2 3 3]

 [4 3 1]

 [0 0 4]

 [2 4 0]

 [3 0 3]

 [1 4 1]

 [4 3 2]

 [1 0 4]]

[[2 2 4]

 [3 4 3]

 [2 3 3]

 [4 3 1]

 [0 0 4]

 [2 4 0]

 [3 0 3]

 [1 4 1]

 [4 3 2]

 [1 0 4]]

[[2 2 4]

 [3 4 3]

 [2 3 3]

 [4 3 1]

 [0 0 4]

 [2 4 0]

 [3 0 3]

 [1 4 1]

 [4 3 2]

 [1 0 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [401]:
intVector = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(intVector[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]

 [0 0 0 0 0 0 0 1]

 [0 0 0 0 0 0 1 0]

 [0 0 0 0 0 0 1 1]

 [0 0 0 0 1 1 1 1]

 [0 0 0 1 0 0 0 0]

 [0 0 1 0 0 0 0 0]

 [0 1 0 0 0 0 0 0]

 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [402]:
matrix = np.random.randint(0,2,(6,3))
uniqueMatrix = np.unique(matrix, axis=0)
print(uniqueMatrix)

[[0 0 1]

 [0 1 0]

 [0 1 1]

 [1 0 0]

 [1 0 1]

 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [403]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.17864169, 0.01069083, 0.08559957, 0.05122869, 0.093887  ,
        0.01645558, 0.05053881, 0.04341809, 0.08745473, 0.02039859],
       [0.81655555, 0.04886687, 0.39126813, 0.23416187, 0.42914929,
        0.075217  , 0.23100849, 0.19846032, 0.39974795, 0.09324016],
       [0.34832873, 0.02084578, 0.16690834, 0.09988948, 0.1830678 ,
        0.03208629, 0.0985443 , 0.0846598 , 0.17052569, 0.03977467],
       [0.37319231, 0.02233374, 0.1788222 , 0.10701955, 0.19613511,
        0.0343766 , 0.10557836, 0.09070279, 0.18269775, 0.04261377],
       [0.28467429, 0.01703637, 0.1364071 , 0.08163543, 0.14961354,
        0.02622277, 0.08053607, 0.06918886, 0.13936341, 0.03250615],
       [0.13240509, 0.0079238 , 0.06344442, 0.03796952, 0.06958688,
        0.01219649, 0.0374582 , 0.03218049, 0.06481943, 0.01511896],
       [0.60110862, 0.03597342, 0.28803264, 0.17237862, 0.31591891,
        0.05537111, 0.17005726, 0.14609687, 0.29427507, 0.06863889],
       [0.09641016, 0.00576968, 0.0461967

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [404]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)               
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)      
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [413]:
X = np.asarray([[4.0, 2.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [407]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[0.00249408 0.37115575]
